avatar:
  img: /images/avatar.jpg
  rounded: true
  opacity: 1

# Social media links
social:
  GitHub: https://github.com/shangdizhiying || fab fa-github
  邮箱: mailto:test@example.com || fas fa-envelope
  order_by: social

CDN:
  css:
    fontawesome: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css

valine:
  enable: false
  #appId: zYhT7FrgJSPZN7a7ItDM7Z8h-gzGzoHsz
  #appKey: 9WgNyNYFCRNyIssApCH46nv1
  #cdn: /js/Valine.min.js
  #placeholder: 说点什么吧～
  #avatar: mm
  #meta: [nick, mail, link]
  #pageSize: 10
  #lang: zh-cn
  #visitor: true
  #recordIP: false