avatar:
  img: /images/avatar.jpg
  rounded: true
  opacity: 1

# Social media links
social:
  GitHub: https://github.com/shangdizhiying || fab fa-github
  邮箱: mailto:test@example.com || fas fa-envelope
  order_by: social

# Valine评论系统配置
valine:
  enable: true
  appId: ZIszPZW5EcHVo7qHIHNvIooA-MdYXbMMI
  appKey: M2E6rqYbGv5xQ2zf3OA1aoIT
  placeholder: 说点什么吧～ # 评论框占位文字
  avatar: mm # 头像样式 (mm, identicon, monsterid, wavatar, retro, robohash)
  meta: [nick, mail, link] # 评论者信息
  pageSize: 10 # 每页评论数量
  lang: zh-cn # 语言
  visitor: true # 文章阅读量统计
  recordIP: false # 记录评论者IP
  serverURLs: https://ziszpzw5.api.lncldglobal.com